name: Docker Image CI

on:
  push:
    branches: ["UAT_DEPLOY"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deplopy Via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SSH_HOST}}
          username: root
          key: ${{secrets.SSH_KEY}}
          script: |
            cd /root/projects/nodejs-application-deploy-github-actions
            git pull
            docker compose up -d --build
